name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: git submodule update --init --recursive
    - name: run with archlinux docker img
      uses: docker://archlinux/base:latest
      with:
        entrypoint: ./.github/actions/entrypoint.sh
    - name: run with fedora docker img
      uses: docker://fedora:latest
      with:
        entrypoint: ./.github/actions/entrypoint-fedora.sh
